version: "3.0"


services:
  web:
    build: .
    restart: on-failure
    ports: 
      - 5003:80
    networks:
      - api_network


networks:
  api_network:
    name: germany-city-api_default
    external: true